### PR TITLE
feat: add config option to enable/disable updating window.history

### PR DESCRIPTION
**Pull request by jwhitmarsh**
Firstly, thanks for this plugin, it's very helpful. 

This PR is a first cut at solving the requirement in #3 and #7. It's backwards compatible, and defaults to your desired behaviour @Yuliang-Lee, but enables the user to prevent `window.history` being updated if required. 

The change means that you can set a global config option like: 
```js
Vue.use(vueSmoothScroll, { updateHistory: false });
```

Or you can do it on a per-usage basis:
```html
<div id="container">
  <a href="#div-id" v-smooth-scroll="{ updateHistory: false }">Anchor</a>
  <div id="div-id"></div>
</div>
```

You can also set a global and then override the global in the per-usage config. 

Let me know what you think!

### CODE REVIEW

**Comment by Yuliang-Lee** [comment]
Thanks your PR!

**Comment by jwhitmarsh** [comment]
My pleasure @Yuliang-Lee, glad you liked the solution :)

Are you planning on publishing to npm with the last two fixes? Or are you waiting on some other issues to be resolved?

**Comment by Yuliang-Lee** [comment]
published

**Comment by tabathap** [comment]
👌

**Pull request merged**
